import {defaultProjects,buildTrails,coUsage,validateProjects,removeSpace,restoreSpace} from './insights.js';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=t=>new Date(t).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
const clock=t=>new Date(t).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',second:'2-digit'});
export function tagNames(tags,projects){return (tags||[]).map(t=>{const p=projects.find(p=>p.id===t.projectId);return p?p.name+(t.topic?' / '+t.topic:''):'';}).filter(Boolean);}
const pills=(tags,projects)=>tagNames(tags,projects).map(n=>'<span class="pill">'+esc(n)+'</span>').join(' ');
let projectFilter='__tagged';
export function renderInsights(view,state,plan,query=''){
 const projects=state.projects||defaultProjects,reports=state.analysisReports||[],latest=reports[0],trails=buildTrails(state.events,state.historyImport,state.analysisSource||'foreground');
 if(view==='projects')return `<div class="section-heading"><h2>告诉 AI，你经常在做什么</h2><button id="new-project" class="button primary">＋ 常用项目</button></div><div class="timeline-guide"><p>项目说明帮助 AI 理解用途；细分标签用于进一步区分。一次活动可以同时关联「评测研究」与「论文阅读」。修改后，下一次 AI 分析使用新配置。</p></div><div class="space-grid">${projects.map(p=>`<article class="list-card"><h3>${esc(p.name)}</h3><p>${esc(p.description)||'尚未填写说明'}</p><div>${p.children.map(c=>'<span class="pill">'+esc(c)+'</span>').join(' ')}</div><div class="agent-actions"><button class="button secondary" data-project-edit="${esc(p.id)}">编辑项目与细分</button><button class="button secondary" data-project-delete="${esc(p.id)}">移除项目</button></div></article>`).join('')}</div>`;
 if(view==='overview'){
  const counts=projects.map(p=>({p,count:new Set(plan.groups.filter(g=>g.tags?.some(t=>t.projectId===p.id)).flatMap(g=>g.tabIds)).size}));
  const links=coUsage(trails);
  return `<div class="insight-grid"><section class="list-card"><h3>常用项目分布</h3><p>当前打开页面；允许多标签，项目数量不可相加。</p>${counts.map(({p,count})=>`<div class="distribution"><span>${esc(p.name)}</span><meter min="0" max="${Math.max(1,state.tabs.length)}" value="${count}"></meter><b>${count} 页</b></div>`).join('')}<p>${latest?'项目关联来自最近一次 AI 分析；新增页等待更新。':'首次 AI 分析后，这里显示页面与常用项目的关联。'}</p><button class="button secondary" data-view="projects">调整常用项目</button></section><section class="list-card"><h3>浏览活动线索</h3><div class="insight-number">${latest?.activities?.length||0}<small> 次已分析活动</small></div><p>本次可用样本：${trails.length} 段 / ${trails.reduce((n,t)=>n+t.visits.length,0)} 次访问。最多取最近 20 段、300 次访问，每段最多 60 次。</p><p>同一项目的多次浏览分别保留。这里只用于关联页面，不计算工作时长或效率。</p><button data-view="analysis" class="button secondary">查看 AI 分析</button></section></div><section class="list-card"><h3>经常前后看的页面</h3><p>在所选来源的样本里，两个页面相邻出现过多少段。只是共同访问线索，是否同一任务由 AI 结合内容判断。</p>${links.length?links.map(p=>`<div class="affinity-row"><span>${esc(p.a.title||p.a.url)}<br><small>↔ ${esc(p.b.title||p.b.url)}</small></span><b>${p.count} 段</b></div>`).join(''):'<p>还没有足够的相邻访问线索。</p>'}</section>`;
 }
 const input=`<section class="list-card"><h3>这次让 AI 参考什么</h3><div class="analysis-input"><label>关联线索来源 <select id="analysis-source"><option value="foreground" ${(state.analysisSource||'foreground')==='foreground'?'selected':''}>前台切换线索</option><option value="history" ${state.analysisSource==='history'?'selected':''}>已导入的 Chrome 历史</option><option value="both" ${state.analysisSource==='both'?'selected':''}>两种线索（分开分析）</option></select></label><button id="import-history" class="button secondary">读取最近 7 天 Chrome 历史</button><button id="pause" class="button secondary">${state.paused?'继续记录切换线索':'暂停记录切换线索'}</button></div><p>当前页面标题、过滤参数的网址、常用项目与所选访问路径，会在点击「AI 分析并更新」时发送到已配置的模型 API。读取历史按钮只导入本机，首次使用由 Chrome 请求权限。</p><p>${state.historyImport?`上次导入 ${date(state.historyImport.at)} · ${state.historyImport.visits.length} 次访问。${esc(state.historyImport.scope)} <button id="clear-import" class="text-button">清除本机导入副本</button>`:'尚未导入 Chrome 历史。历史能补充导航访问，无法还原已打开标签之间的来回切换。'}</p><small>前台线索${state.paused?'已暂停':'已开启'}；原始线索保留最多 30 天。分析报告保留最近 5 次，并受总大小限制。</small></section>`;
 if(!latest)return input+'<div class="empty"><h3>把页面与每次浏览的来路连起来</h3><p>点击上方 AI 分析并更新，生成项目分类、分析依据和分别命名的浏览活动。</p></div>';
 const activities=(latest.activities||[]).filter(a=>(!projectFilter||(projectFilter==='__tagged'?a.tags.length>0:a.tags.some(t=>t.projectId===projectFilter)))&&(!query||JSON.stringify(a).toLowerCase().includes(query.toLowerCase())));
 return input+`<section class="list-card"><h3>AI 分析 · ${date(latest.at)}</h3><p>${esc(latest.summary)}</p><small>${esc(latest.model)} · ${latest.scope.tabCount} 个页面 · ${latest.scope.trailCount} 段路径 / ${latest.scope.visitCount} 次访问 · 仅根据标题、网址和访问顺序推断</small></section><div class="section-heading"><h2>每一次浏览活动 · ${activities.length}</h2><select id="activity-project" aria-label="筛选活动项目"><option value="__tagged" ${projectFilter==='__tagged'?'selected':''}>与常用项目有关</option><option value="" ${projectFilter===''?'selected':''}>全部活动（含日常）</option>${(latest.projects||projects).map(p=>`<option value="${esc(p.id)}" ${projectFilter===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div><p class="muted">共 ${latest.activities.length} 次活动，当前显示 ${activities.length} 次。默认只看与常用项目有关的活动。每张卡片是一次连续活动；同名项目的不同轮次不会合并。展开后按访问顺序阅读，重复访问仍然保留。名称与分段是 AI 推断。</p>${activities.map(a=>`<article class="list-card activity-card"><div class="activity-top"><h3>${esc(a.name)}</h3><span>${date(a.visits[0].ts)} — ${clock(a.visits.at(-1).ts)}</span></div><div>${pills(a.tags,latest.projects||projects)} <span class="pill">${a.source==='history'?'Chrome 历史':'前台切换'}</span></div><p>${esc(a.reason)}</p><div class="path-preview">${a.visits.slice(0,4).map(v=>'<span>'+esc(v.title||v.url)+'</span>').join('<b>→</b>')}${a.visits.length>4?'<b>…</b>':''}</div><details><summary>查看完整路径 · ${a.visits.length} 次访问${a.truncated?' · 输入段仅取末尾访问':''}</summary><ol class="activity-path">${a.visits.map((v,i)=>`<li><time>${clock(v.ts)}</time><div><strong>${a.visits.slice(0,i).some(old=>old.url===v.url)?'↩ 再次访问 · ':''}${esc(v.title||v.url)}</strong><small>${esc(v.url)}</small></div></li>`).join('')}</ol></details></article>`).join('')}${!activities.length?'<p>当前筛选下没有已分析活动。未采集线索时，仍会更新页面分类。</p>':''}<details class="list-card"><summary>本次工作空间的分类依据</summary>${latest.groups.map(g=>`<h4>${esc(g.name)} ${pills(g.tags,latest.projects||projects)}</h4><p>${esc(g.reason)}</p>`).join('')}</details><details class="list-card"><summary>之前的分析 · ${Math.max(0,reports.length-1)} 次</summary>${reports.slice(1).map(r=>`<h4>${date(r.at)}</h4><p>${esc(r.summary)}</p>${(r.activities||[]).map(a=>`<details><summary>${esc(a.name)} · ${date(a.visits[0].ts)} · ${a.visits.length} 次访问</summary><ol>${a.visits.map(v=>'<li>'+clock(v.ts)+' '+esc(v.title||v.url)+'</li>').join('')}</ol>`).join('')}`).join('')}</details><button class="button secondary" data-view="timeline">查看原始切换线索</button>`;
}
export function archivedSpaces(state){return (state.archivedGroups||[]).length?'<details class="list-card"><summary>已移除的工作空间 · 可恢复</summary>'+state.archivedGroups.map(a=>`<div class="affinity-row"><span>${esc(a.group.name)} · ${date(a.at)}</span><button data-space-restore="${esc(a.id)}" class="button secondary">恢复分类</button></div>`).join('')+'</details>':'';}
export async function insightAction(target,ctx){
 const {state,plan,modal,api,refresh,save,live}=ctx,projects=state.projects||defaultProjects;
 const id=target.id;
 if(target.dataset.projectEdit||id==='new-project'){
  const p=projects.find(p=>p.id===target.dataset.projectEdit)||{id:crypto.randomUUID(),name:'',description:'',children:[]};
  modal('常用项目与细分',`<div class="project-form"><label>项目名称<input id="project-name" maxlength="60" value="${esc(p.name)}"></label><label>它通常包含什么<textarea id="project-description" maxlength="1000">${esc(p.description)}</textarea></label><label>细分标签（每行一个，可留空）<textarea id="project-children">${esc(p.children.join('\n'))}</textarea></label><p>细分仅作为 AI 参考，可以随时调整。一段活动可以关联多个项目。</p></div>`,`<button id="save-project" data-project-id="${esc(p.id)}" class="button primary">保存项目</button>`);return true;
 }
 if(id==='save-project'){const p={id:target.dataset.projectId,name:document.querySelector('#project-name').value,description:document.querySelector('#project-description').value,children:document.querySelector('#project-children').value.split('\n').map(s=>s.trim()).filter(Boolean)};await api('saveProjects',{projects:validateProjects([...projects.filter(x=>x.id!==p.id),p])});document.querySelector('#modal').close();await refresh();return true;}
 if(target.dataset.projectDelete){modal('移除常用项目？','<p>以后分析不再参考这个项目。当前工作空间和已有分析报告保留。</p>',`<button id="confirm-project-delete" data-project-id="${esc(target.dataset.projectDelete)}" class="button danger">移除项目</button>`);return true;}
 if(id==='confirm-project-delete'){await api('saveProjects',{projects:projects.filter(p=>p.id!==target.dataset.projectId)});document.querySelector('#modal').close();await refresh();return true;}
 if(id==='import-history'){if(!live){ctx.toast('演示不会读取真实 Chrome 历史。');return true;}if(!await chrome.permissions.request({permissions:['history']})){ctx.toast('未授权读取历史，已有线索保留。');return true;}target.disabled=true;target.textContent='正在导入…';try{await api('importHistory');await refresh();}finally{target.disabled=false;target.textContent='读取最近 7 天 Chrome 历史';}return true;}
 if(id==='clear-import'){await api('clearHistoryImport');await refresh();return true;}
 if(target.dataset.spaceRemove){modal('移除这个工作空间？','<p>只移除分类，里面的页面进入「未分配」，不会关闭标签页。浏览活动和分析报告保留；可在工作空间底部恢复分类。</p>',`<button id="confirm-space-remove" data-space-id="${esc(target.dataset.spaceRemove)}" class="button danger">移除分类，页面保留</button>`);return true;}
 if(id==='confirm-space-remove'){const next=removeSpace(plan,target.dataset.spaceId,state.tabs);await save(next.plan,[next.archive,...(state.archivedGroups||[])]);document.querySelector('#modal').close();await refresh();return true;}
 if(target.dataset.spaceRestore){const a=state.archivedGroups.find(a=>a.id===target.dataset.spaceRestore);await save(restoreSpace(plan,a,state.tabs),state.archivedGroups.filter(x=>x.id!==a.id));await refresh();return true;}
 return false;
}
export async function insightChange(target,ctx){if(target.id==='activity-project'){projectFilter=target.value;ctx.render();return;}if(target.id==='analysis-source'){await ctx.api('analysisSource',{value:target.value});await ctx.refresh();}}
