import {test,expect} from '@playwright/test';
import {defaultProjects} from '../extension/insights.js';
test('projects can be edited and removed; workspace removal restores without closing pages; reports retain repeated paths on desktop and mobile',async({page})=>{
 await page.goto('http://127.0.0.1:4173');
 await page.locator('[data-view="projects"]').click();await expect(page.getByRole('heading',{name:'论文阅读',exact:true})).toBeVisible();
 await page.locator('[data-project-edit="papers"]').click();await page.locator('#project-children').fill('方法与结论\n案例应用');await page.locator('#save-project').click();await expect(page.locator('#content')).toContainText('案例应用');
 await page.locator('#new-project').click();await page.locator('#project-name').fill('临时研究');await page.locator('#project-description').fill('只用于这轮验证');await page.locator('#save-project').click();await expect(page.getByRole('heading',{name:'临时研究'})).toBeVisible();
 const card=page.locator('.list-card').filter({has:page.getByRole('heading',{name:'临时研究'})});await card.getByRole('button',{name:'移除项目',exact:true}).click();await page.locator('#confirm-project-delete').click();await expect(page.getByRole('heading',{name:'临时研究'})).toHaveCount(0);
 await page.screenshot({path:'artifacts/pagefold-projects-v0.4.1.png',fullPage:true});
 await page.locator('.primary-nav [data-view="spaces"]').click();const before=await page.locator('[data-rename]').first().inputValue();const count=await page.locator('.tab-list .tab-row').count();await page.locator('[data-space-remove]').first().click();await page.locator('#confirm-space-remove').click();await expect(page.locator('.tab-list .tab-row')).toHaveCount(count);await expect(page.locator('[data-rename][value="未分配"]')).toHaveCount(1);await page.getByText('已移除的工作空间 · 可恢复').click();await page.locator('[data-space-restore]').click();await expect(page.locator(`[data-rename][value="${before}"]`)).toHaveCount(1);await expect(page.locator('.tab-list .tab-row')).toHaveCount(count);
 const now=Date.now();const visits=[{ts:now-60000,title:'GPT6 案例',url:'https://example.com/cases'},{ts:now-40000,title:'社媒展示',url:'https://example.com/social'},{ts:now-20000,title:'GPT6 案例',url:'https://example.com/cases'}];
 await page.evaluate(({projects,visits,now})=>{const d=JSON.parse(localStorage.getItem('pagefold-demo'));d.analysisReports=[{id:'report',at:now,model:'测试报告',summary:'两次独立的案例调研；论文阅读同时服务于评测研究。',projects,scope:{tabCount:d.tabs.length,trailCount:2,visitCount:4},groups:d.draft.plan.groups,activities:[{id:'one',name:'GPT6 案例与社媒',source:'foreground',tags:[{projectId:'social',topic:''}],reason:'按相邻访问与返回关系判断',visits},{id:'two',name:'GPT6 案例与社媒',source:'foreground',tags:[{projectId:'social',topic:''}],reason:'同项目的另一次独立访问',visits:[{...visits[0],ts:now-3600000}]}]}];localStorage.setItem('pagefold-demo',JSON.stringify(d));},{projects:defaultProjects,visits,now});
 await page.reload();await page.locator('[data-view="analysis"]').click();await expect(page.locator('.activity-card')).toHaveCount(2);await page.locator('.activity-card details').first().locator('summary').click();await expect(page.locator('.activity-path').first().locator('li')).toHaveCount(3);await expect(page.locator('.activity-path').first()).toContainText('再次访问');await page.locator('#activity-project').selectOption('papers');await expect(page.locator('.activity-card')).toHaveCount(0);await page.locator('#activity-project').selectOption('');
 await page.screenshot({path:'artifacts/pagefold-analysis-v0.4.1.png',fullPage:true});
 await page.locator('.primary-nav [data-view=spaces]').click();await page.locator('[data-view="overview"]').first().click();await expect(page.getByRole('heading',{name:'经常前后看的页面'})).toBeVisible();await page.screenshot({path:'artifacts/pagefold-overview-v0.4.1.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.locator('#mobile-nav').selectOption('analysis');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:'artifacts/pagefold-analysis-mobile-v0.4.1.png',fullPage:true});
});
